name: Hourly AQHI Grid

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pandas \
            geopandas \
            scipy \
            numpy \
            shapely \
            matplotlib \
            requests
      - name: Run preprocessing
        run: python aqhi_map.py
      - name: Commit & push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add interpolated_grid.geojson
          git commit --allow-empty -m "Republish Pages to include GeoJSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
